### ISSUE TITLE
Had hard time build

### ISSUE THREAD

**Issue by YuxinxinChen** [gpudirect/libgdsync#45]
From the instruction:
```bash
Git repository does not include autotools files. The first time the directory must be configured by running autogen.sh

As an example, the build.sh script is provided. You should modify it according to the desired destination paths as well as the location of the dependencies.

Before starting to build LibGDSync, you need to have available on your system GDRCopy libraries and headers.
```
I need to install GDRCopy and modify the build.sh correspondingly and execute ./build.sh
However, in build.sh:
```bash
#!/bin/bash

[ ! -d config ] && mkdir -p config

[ ! -e configure ] && ./autogen.sh

[ ! -d build ] && mkdir build

cd build
echo "CUDADRV=$CUDADRV"
if [ ! -e Makefile ]; then
    echo "configuring..."
    ../configure \
        --prefix=$PREFIX \
        --with-libibverbs=$PREFIX \
        --with-cuda-driver=$CUDADRV \
        --with-cuda-toolkit=$CUDA \
        --with-gdrcopy=$PREFIX \
        --with-mpi=$MPI_HOME \
        --enable-test

fi

make V=1 clean all install
```
I guess I need to $CUDADRV to cuda drive path, $CUDA to cuda path, $MPI_HOME to openMPI path. But what is the $PREFIX?

Also what MPI you are using? Which version?

Thanks!

**Comment by e-ago** [comment]
It seems that you are using the master branch; please switch to the devel branch because is the most updated.
Considering the configure.ac file, with `--prefix=$PREFIX` you are specifying that you want to install LibGDSync
- headers in $PREFIX/include
- libs in $PREFIX/lib
- bins in $PREFIX/bin

With `--with-libibverbs=$PREFIX` you are you are specifying that libibverbs libs and headers are in $PREFIX/lib and $PREFIX/include directories.

With `--with-gdrcopy=$PREFIX` you are you are specifying that GDRCopy libs and headers are in $PREFIX/lib and $PREFIX/include directories.
 
It is not required to have the same path for libibverbs, gdrcopy and libgdsync, thus you can customize them as you prefer.

We use all OpenMPI versions (1.10, 2.x ad 3.x).

**Comment by YuxinxinChen** [comment]
thanks!
